# This is a basic workflow that is manually triggered

name: Test:nft

on:
  push:
    paths-ignore:
      - "examples/**"
      - "README.md"
      # - ".github/workflows/*.yml"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
   # - run: npm ci
    - run: |
        cd ./packages/shared/
        NODE_ENV=standalone ./solana-suite-config.js debug on
        cat ${{secrets.SOLANA_CUSTOM_URL}}
        NODE_ENV=standalone ./solana-suite-config.js cluster custom ${{secrets.SOLANA_CUSTOM_URL}}
        echo src/solana-suite.json
#    - run: npm run test:nft
