# This is a basic workflow that is manually triggered

name: Test:core

on:
  push:
    paths-ignore:
      - "examples/**"
      - "README.md"
    branches: [ main ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: ls
    - run: cd node_modules/@solana-suite/shared/ 
    - run: ./solana-suite-config.js cluster custom ${{secrets.SOLANA_CUSTOM_URL}}
    - run: npm run test:core
